### PR TITLE
#WIP First setup of Data Organization, and covert keyring tacklebox and leprechaun #16

### LINKED ISSUE #16: Storable Item Collection Data Organization
Each location could probably implement an abstract class if Java allows enum inheritance.

### PR DESCRIPTION
**Pull request by BramManuel**
closes #16

This is a draft PR.
I want to check if you agree with this solution? before i make allot of new enums for all the storage locations.

### CODE REVIEW

**Comment by mcgeer** [comment]
Nice abstraction, I think this is a better impl. The single file instantiation of all items in StorableItem was kinda clunky.

**Comment by mcgeer** [comment]
https://regexr.com/825cd

Whipped this together to transform my data instantiation to yours. Go to list, you need to modify the main area by adding a space or something if the query takes to long and it will then load.

**Comment by mcgeer** [comment]
image

**Comment by BramManuel** [comment]
I did the same with find and replace in IntelliJ:
`, (?<=\(\s*ItemID\.\w+,\s*)\w+\.\w+(?=\s*\))`

Will be working on this again on friday evening!

**Comment by mcgeer** [comment]
I can take this on tomorrow. Is this at the point where you are happy with it and expect no further changes?

**Comment by mcgeer** [comment]
Merged to Master, will make the official change to plugin hub after we have the additional changes.

**Pull request merged**
